[tool.black]
line-length = 110
target-versions = ['py39']
skip-string-normalization = true

[tool.isort]
profile = "black"
src_paths = ["solutions"]
combine_as_imports = true
line_length = 110
sections = [
    'FUTURE',
    'STDLIB',
    'THIRDPARTY',
    'FIRSTPARTY',
    'LOCALFOLDER'
]
